/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SMARTVASE_SMARTVASE_PB_H_INCLUDED
#define PB_SMARTVASE_SMARTVASE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* ===================================================================
 Enums Globali
 =================================================================== */
typedef enum _smartvase_MovementState {
    smartvase_MovementState_M_IDLE = 0,
    smartvase_MovementState_M_MOVING = 1,
    smartvase_MovementState_M_AVOID_START = 2,
    smartvase_MovementState_M_AVOID_REVERSING = 3,
    smartvase_MovementState_M_AVOID_TURNING = 4,
    smartvase_MovementState_M_STUCK = 5
} smartvase_MovementState;

typedef enum _smartvase_Log_LogLevel {
    smartvase_Log_LogLevel_INFO = 0,
    smartvase_Log_LogLevel_WARN = 1,
    smartvase_Log_LogLevel_ERROR = 2,
    smartvase_Log_LogLevel_CRITICAL = 3
} smartvase_Log_LogLevel;

typedef enum _smartvase_CommandResponse_Status {
    smartvase_CommandResponse_Status_OK = 0,
    smartvase_CommandResponse_Status_ERROR = 1
} smartvase_CommandResponse_Status;

typedef enum _smartvase_SetModeCommand_Mode {
    smartvase_SetModeCommand_Mode_IDLE = 0,
    smartvase_SetModeCommand_Mode_LIGHT = 1,
    smartvase_SetModeCommand_Mode_SHADOW = 2
} smartvase_SetModeCommand_Mode;

/* Struct definitions */
/* ===================================================================
 Messaggi Atomici
 =================================================================== */
typedef struct _smartvase_TelemetryFast {
    float front_dist_cm;
    int32_t lux;
    smartvase_MovementState movement_state;
    float left_dist_cm;
    float right_dist_cm;
    float water_level_cm;
    char device_id[16];
} smartvase_TelemetryFast;

typedef struct _smartvase_TelemetryDeep {
    float temperature_c;
    float humidity_percent;
    float pressure_hpa;
    uint32_t gas_resistance_ohms;
    uint32_t uptime_s;
    uint32_t free_ram_bytes;
    uint32_t watchdog_resets;
    uint32_t total_irrigations;
    uint32_t obstacles_avoided;
    uint32_t stuck_events;
    uint32_t bme_read_errors;
    uint32_t log_overflows;
    uint32_t total_irrigation_duration_s;
    uint32_t total_motor_active_time_s;
    uint32_t pb_decode_failures;
    char device_id[16];
    /* NUOVO CAMPO */
    float battery_voltage;
} smartvase_TelemetryDeep;

typedef struct _smartvase_Log {
    smartvase_Log_LogLevel level;
    char event[24];
    char detail[32];
    uint32_t timestamp_ms;
    char source_device[16];
} smartvase_Log;

typedef struct _smartvase_Heartbeat {
    uint32_t uptime_s;
    bool is_degraded;
    char device_id[16];
} smartvase_Heartbeat;

typedef struct _smartvase_CommandResponse {
    smartvase_CommandResponse_Status status;
    char detail[64];
    uint32_t cmd_id;
    uint32_t exec_time_ms;
} smartvase_CommandResponse;

/* ===================================================================
 Definizioni dei Comandi Specifici
 =================================================================== */
typedef struct _smartvase_WaterCommand {
    uint32_t duration_ms;
} smartvase_WaterCommand;

typedef struct _smartvase_SetModeCommand {
    smartvase_SetModeCommand_Mode mode;
} smartvase_SetModeCommand;

typedef struct _smartvase_SetMotionParamsCommand {
    uint32_t reverse_ms;
    uint32_t turn_ms;
} smartvase_SetMotionParamsCommand;

typedef struct _smartvase_StopCommand {
    char dummy_field;
} smartvase_StopCommand;

typedef struct _smartvase_RequestDiagnosticsCommand {
    char dummy_field;
} smartvase_RequestDiagnosticsCommand;

typedef struct _smartvase_ReadSoilCommand {
    char dummy_field;
} smartvase_ReadSoilCommand;

typedef struct _smartvase_SoftResetCommand {
    char dummy_field;
} smartvase_SoftResetCommand;

/* ===================================================================
 Comandi e Risposte
 =================================================================== */
typedef struct _smartvase_Command {
    pb_size_t which_command_type;
    union {
        smartvase_WaterCommand water;
        smartvase_SetModeCommand set_mode;
        smartvase_StopCommand stop;
        smartvase_RequestDiagnosticsCommand request_diagnostics;
        smartvase_SetMotionParamsCommand set_motion_params;
        smartvase_ReadSoilCommand read_soil;
        smartvase_SoftResetCommand soft_reset;
    } command_type;
    uint32_t cmd_id;
} smartvase_Command;

/* ===================================================================
 Messaggio Contenitore (Wrapper)
 =================================================================== */
typedef struct _smartvase_WrapperMessage {
    pb_size_t which_payload;
    union {
        smartvase_TelemetryFast telemetry_fast;
        smartvase_TelemetryDeep telemetry_deep;
        smartvase_Log log;
        smartvase_Command command;
        smartvase_CommandResponse command_response;
        smartvase_Heartbeat heartbeat;
    } payload;
} smartvase_WrapperMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _smartvase_MovementState_MIN smartvase_MovementState_M_IDLE
#define _smartvase_MovementState_MAX smartvase_MovementState_M_STUCK
#define _smartvase_MovementState_ARRAYSIZE ((smartvase_MovementState)(smartvase_MovementState_M_STUCK+1))

#define _smartvase_Log_LogLevel_MIN smartvase_Log_LogLevel_INFO
#define _smartvase_Log_LogLevel_MAX smartvase_Log_LogLevel_CRITICAL
#define _smartvase_Log_LogLevel_ARRAYSIZE ((smartvase_Log_LogLevel)(smartvase_Log_LogLevel_CRITICAL+1))

#define _smartvase_CommandResponse_Status_MIN smartvase_CommandResponse_Status_OK
#define _smartvase_CommandResponse_Status_MAX smartvase_CommandResponse_Status_ERROR
#define _smartvase_CommandResponse_Status_ARRAYSIZE ((smartvase_CommandResponse_Status)(smartvase_CommandResponse_Status_ERROR+1))

#define _smartvase_SetModeCommand_Mode_MIN smartvase_SetModeCommand_Mode_IDLE
#define _smartvase_SetModeCommand_Mode_MAX smartvase_SetModeCommand_Mode_SHADOW
#define _smartvase_SetModeCommand_Mode_ARRAYSIZE ((smartvase_SetModeCommand_Mode)(smartvase_SetModeCommand_Mode_SHADOW+1))

#define smartvase_TelemetryFast_movement_state_ENUMTYPE smartvase_MovementState


#define smartvase_Log_level_ENUMTYPE smartvase_Log_LogLevel



#define smartvase_CommandResponse_status_ENUMTYPE smartvase_CommandResponse_Status


#define smartvase_SetModeCommand_mode_ENUMTYPE smartvase_SetModeCommand_Mode








/* Initializer values for message structs */
#define smartvase_TelemetryFast_init_default     {0, 0, _smartvase_MovementState_MIN, 0, 0, 0, ""}
#define smartvase_TelemetryDeep_init_default     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0}
#define smartvase_Log_init_default               {_smartvase_Log_LogLevel_MIN, "", "", 0, ""}
#define smartvase_Heartbeat_init_default         {0, 0, ""}
#define smartvase_Command_init_default           {0, {smartvase_WaterCommand_init_default}, 0}
#define smartvase_CommandResponse_init_default   {_smartvase_CommandResponse_Status_MIN, "", 0, 0}
#define smartvase_WaterCommand_init_default      {0}
#define smartvase_SetModeCommand_init_default    {_smartvase_SetModeCommand_Mode_MIN}
#define smartvase_SetMotionParamsCommand_init_default {0, 0}
#define smartvase_StopCommand_init_default       {0}
#define smartvase_RequestDiagnosticsCommand_init_default {0}
#define smartvase_ReadSoilCommand_init_default   {0}
#define smartvase_SoftResetCommand_init_default  {0}
#define smartvase_WrapperMessage_init_default    {0, {smartvase_TelemetryFast_init_default}}
#define smartvase_TelemetryFast_init_zero        {0, 0, _smartvase_MovementState_MIN, 0, 0, 0, ""}
#define smartvase_TelemetryDeep_init_zero        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0}
#define smartvase_Log_init_zero                  {_smartvase_Log_LogLevel_MIN, "", "", 0, ""}
#define smartvase_Heartbeat_init_zero            {0, 0, ""}
#define smartvase_Command_init_zero              {0, {smartvase_WaterCommand_init_zero}, 0}
#define smartvase_CommandResponse_init_zero      {_smartvase_CommandResponse_Status_MIN, "", 0, 0}
#define smartvase_WaterCommand_init_zero         {0}
#define smartvase_SetModeCommand_init_zero       {_smartvase_SetModeCommand_Mode_MIN}
#define smartvase_SetMotionParamsCommand_init_zero {0, 0}
#define smartvase_StopCommand_init_zero          {0}
#define smartvase_RequestDiagnosticsCommand_init_zero {0}
#define smartvase_ReadSoilCommand_init_zero      {0}
#define smartvase_SoftResetCommand_init_zero     {0}
#define smartvase_WrapperMessage_init_zero       {0, {smartvase_TelemetryFast_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define smartvase_TelemetryFast_front_dist_cm_tag 1
#define smartvase_TelemetryFast_lux_tag          2
#define smartvase_TelemetryFast_movement_state_tag 3
#define smartvase_TelemetryFast_left_dist_cm_tag 4
#define smartvase_TelemetryFast_right_dist_cm_tag 5
#define smartvase_TelemetryFast_water_level_cm_tag 6
#define smartvase_TelemetryFast_device_id_tag    7
#define smartvase_TelemetryDeep_temperature_c_tag 1
#define smartvase_TelemetryDeep_humidity_percent_tag 2
#define smartvase_TelemetryDeep_pressure_hpa_tag 3
#define smartvase_TelemetryDeep_gas_resistance_ohms_tag 4
#define smartvase_TelemetryDeep_uptime_s_tag     5
#define smartvase_TelemetryDeep_free_ram_bytes_tag 6
#define smartvase_TelemetryDeep_watchdog_resets_tag 7
#define smartvase_TelemetryDeep_total_irrigations_tag 8
#define smartvase_TelemetryDeep_obstacles_avoided_tag 9
#define smartvase_TelemetryDeep_stuck_events_tag 10
#define smartvase_TelemetryDeep_bme_read_errors_tag 11
#define smartvase_TelemetryDeep_log_overflows_tag 12
#define smartvase_TelemetryDeep_total_irrigation_duration_s_tag 13
#define smartvase_TelemetryDeep_total_motor_active_time_s_tag 14
#define smartvase_TelemetryDeep_pb_decode_failures_tag 15
#define smartvase_TelemetryDeep_device_id_tag    16
#define smartvase_TelemetryDeep_battery_voltage_tag 17
#define smartvase_Log_level_tag                  1
#define smartvase_Log_event_tag                  2
#define smartvase_Log_detail_tag                 3
#define smartvase_Log_timestamp_ms_tag           4
#define smartvase_Log_source_device_tag          5
#define smartvase_Heartbeat_uptime_s_tag         1
#define smartvase_Heartbeat_is_degraded_tag      2
#define smartvase_Heartbeat_device_id_tag        3
#define smartvase_CommandResponse_status_tag     1
#define smartvase_CommandResponse_detail_tag     2
#define smartvase_CommandResponse_cmd_id_tag     99
#define smartvase_CommandResponse_exec_time_ms_tag 100
#define smartvase_WaterCommand_duration_ms_tag   1
#define smartvase_SetModeCommand_mode_tag        1
#define smartvase_SetMotionParamsCommand_reverse_ms_tag 1
#define smartvase_SetMotionParamsCommand_turn_ms_tag 2
#define smartvase_Command_water_tag              1
#define smartvase_Command_set_mode_tag           2
#define smartvase_Command_stop_tag               3
#define smartvase_Command_request_diagnostics_tag 4
#define smartvase_Command_set_motion_params_tag  5
#define smartvase_Command_read_soil_tag          6
#define smartvase_Command_soft_reset_tag         7
#define smartvase_Command_cmd_id_tag             99
#define smartvase_WrapperMessage_telemetry_fast_tag 1
#define smartvase_WrapperMessage_telemetry_deep_tag 2
#define smartvase_WrapperMessage_log_tag         3
#define smartvase_WrapperMessage_command_tag     4
#define smartvase_WrapperMessage_command_response_tag 5
#define smartvase_WrapperMessage_heartbeat_tag   6

/* Struct field encoding specification for nanopb */
#define smartvase_TelemetryFast_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    front_dist_cm,     1) \
X(a, STATIC,   SINGULAR, INT32,    lux,               2) \
X(a, STATIC,   SINGULAR, UENUM,    movement_state,    3) \
X(a, STATIC,   SINGULAR, FLOAT,    left_dist_cm,      4) \
X(a, STATIC,   SINGULAR, FLOAT,    right_dist_cm,     5) \
X(a, STATIC,   SINGULAR, FLOAT,    water_level_cm,    6) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         7)
#define smartvase_TelemetryFast_CALLBACK NULL
#define smartvase_TelemetryFast_DEFAULT NULL

#define smartvase_TelemetryDeep_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_c,     1) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity_percent,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure_hpa,      3) \
X(a, STATIC,   SINGULAR, UINT32,   gas_resistance_ohms,   4) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_s,          5) \
X(a, STATIC,   SINGULAR, UINT32,   free_ram_bytes,    6) \
X(a, STATIC,   SINGULAR, UINT32,   watchdog_resets,   7) \
X(a, STATIC,   SINGULAR, UINT32,   total_irrigations,   8) \
X(a, STATIC,   SINGULAR, UINT32,   obstacles_avoided,   9) \
X(a, STATIC,   SINGULAR, UINT32,   stuck_events,     10) \
X(a, STATIC,   SINGULAR, UINT32,   bme_read_errors,  11) \
X(a, STATIC,   SINGULAR, UINT32,   log_overflows,    12) \
X(a, STATIC,   SINGULAR, UINT32,   total_irrigation_duration_s,  13) \
X(a, STATIC,   SINGULAR, UINT32,   total_motor_active_time_s,  14) \
X(a, STATIC,   SINGULAR, UINT32,   pb_decode_failures,  15) \
X(a, STATIC,   SINGULAR, STRING,   device_id,        16) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_voltage,  17)
#define smartvase_TelemetryDeep_CALLBACK NULL
#define smartvase_TelemetryDeep_DEFAULT NULL

#define smartvase_Log_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    level,             1) \
X(a, STATIC,   SINGULAR, STRING,   event,             2) \
X(a, STATIC,   SINGULAR, STRING,   detail,            3) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      4) \
X(a, STATIC,   SINGULAR, STRING,   source_device,     5)
#define smartvase_Log_CALLBACK NULL
#define smartvase_Log_DEFAULT NULL

#define smartvase_Heartbeat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_s,          1) \
X(a, STATIC,   SINGULAR, BOOL,     is_degraded,       2) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         3)
#define smartvase_Heartbeat_CALLBACK NULL
#define smartvase_Heartbeat_DEFAULT NULL

#define smartvase_Command_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_type,water,command_type.water),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_type,set_mode,command_type.set_mode),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_type,stop,command_type.stop),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_type,request_diagnostics,command_type.request_diagnostics),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_type,set_motion_params,command_type.set_motion_params),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_type,read_soil,command_type.read_soil),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_type,soft_reset,command_type.soft_reset),   7) \
X(a, STATIC,   SINGULAR, UINT32,   cmd_id,           99)
#define smartvase_Command_CALLBACK NULL
#define smartvase_Command_DEFAULT NULL
#define smartvase_Command_command_type_water_MSGTYPE smartvase_WaterCommand
#define smartvase_Command_command_type_set_mode_MSGTYPE smartvase_SetModeCommand
#define smartvase_Command_command_type_stop_MSGTYPE smartvase_StopCommand
#define smartvase_Command_command_type_request_diagnostics_MSGTYPE smartvase_RequestDiagnosticsCommand
#define smartvase_Command_command_type_set_motion_params_MSGTYPE smartvase_SetMotionParamsCommand
#define smartvase_Command_command_type_read_soil_MSGTYPE smartvase_ReadSoilCommand
#define smartvase_Command_command_type_soft_reset_MSGTYPE smartvase_SoftResetCommand

#define smartvase_CommandResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   SINGULAR, STRING,   detail,            2) \
X(a, STATIC,   SINGULAR, UINT32,   cmd_id,           99) \
X(a, STATIC,   SINGULAR, UINT32,   exec_time_ms,    100)
#define smartvase_CommandResponse_CALLBACK NULL
#define smartvase_CommandResponse_DEFAULT NULL

#define smartvase_WaterCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       1)
#define smartvase_WaterCommand_CALLBACK NULL
#define smartvase_WaterCommand_DEFAULT NULL

#define smartvase_SetModeCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1)
#define smartvase_SetModeCommand_CALLBACK NULL
#define smartvase_SetModeCommand_DEFAULT NULL

#define smartvase_SetMotionParamsCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   reverse_ms,        1) \
X(a, STATIC,   SINGULAR, UINT32,   turn_ms,           2)
#define smartvase_SetMotionParamsCommand_CALLBACK NULL
#define smartvase_SetMotionParamsCommand_DEFAULT NULL

#define smartvase_StopCommand_FIELDLIST(X, a) \

#define smartvase_StopCommand_CALLBACK NULL
#define smartvase_StopCommand_DEFAULT NULL

#define smartvase_RequestDiagnosticsCommand_FIELDLIST(X, a) \

#define smartvase_RequestDiagnosticsCommand_CALLBACK NULL
#define smartvase_RequestDiagnosticsCommand_DEFAULT NULL

#define smartvase_ReadSoilCommand_FIELDLIST(X, a) \

#define smartvase_ReadSoilCommand_CALLBACK NULL
#define smartvase_ReadSoilCommand_DEFAULT NULL

#define smartvase_SoftResetCommand_FIELDLIST(X, a) \

#define smartvase_SoftResetCommand_CALLBACK NULL
#define smartvase_SoftResetCommand_DEFAULT NULL

#define smartvase_WrapperMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,telemetry_fast,payload.telemetry_fast),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,telemetry_deep,payload.telemetry_deep),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,log,payload.log),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,command,payload.command),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,command_response,payload.command_response),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,heartbeat,payload.heartbeat),   6)
#define smartvase_WrapperMessage_CALLBACK NULL
#define smartvase_WrapperMessage_DEFAULT NULL
#define smartvase_WrapperMessage_payload_telemetry_fast_MSGTYPE smartvase_TelemetryFast
#define smartvase_WrapperMessage_payload_telemetry_deep_MSGTYPE smartvase_TelemetryDeep
#define smartvase_WrapperMessage_payload_log_MSGTYPE smartvase_Log
#define smartvase_WrapperMessage_payload_command_MSGTYPE smartvase_Command
#define smartvase_WrapperMessage_payload_command_response_MSGTYPE smartvase_CommandResponse
#define smartvase_WrapperMessage_payload_heartbeat_MSGTYPE smartvase_Heartbeat

extern const pb_msgdesc_t smartvase_TelemetryFast_msg;
extern const pb_msgdesc_t smartvase_TelemetryDeep_msg;
extern const pb_msgdesc_t smartvase_Log_msg;
extern const pb_msgdesc_t smartvase_Heartbeat_msg;
extern const pb_msgdesc_t smartvase_Command_msg;
extern const pb_msgdesc_t smartvase_CommandResponse_msg;
extern const pb_msgdesc_t smartvase_WaterCommand_msg;
extern const pb_msgdesc_t smartvase_SetModeCommand_msg;
extern const pb_msgdesc_t smartvase_SetMotionParamsCommand_msg;
extern const pb_msgdesc_t smartvase_StopCommand_msg;
extern const pb_msgdesc_t smartvase_RequestDiagnosticsCommand_msg;
extern const pb_msgdesc_t smartvase_ReadSoilCommand_msg;
extern const pb_msgdesc_t smartvase_SoftResetCommand_msg;
extern const pb_msgdesc_t smartvase_WrapperMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define smartvase_TelemetryFast_fields &smartvase_TelemetryFast_msg
#define smartvase_TelemetryDeep_fields &smartvase_TelemetryDeep_msg
#define smartvase_Log_fields &smartvase_Log_msg
#define smartvase_Heartbeat_fields &smartvase_Heartbeat_msg
#define smartvase_Command_fields &smartvase_Command_msg
#define smartvase_CommandResponse_fields &smartvase_CommandResponse_msg
#define smartvase_WaterCommand_fields &smartvase_WaterCommand_msg
#define smartvase_SetModeCommand_fields &smartvase_SetModeCommand_msg
#define smartvase_SetMotionParamsCommand_fields &smartvase_SetMotionParamsCommand_msg
#define smartvase_StopCommand_fields &smartvase_StopCommand_msg
#define smartvase_RequestDiagnosticsCommand_fields &smartvase_RequestDiagnosticsCommand_msg
#define smartvase_ReadSoilCommand_fields &smartvase_ReadSoilCommand_msg
#define smartvase_SoftResetCommand_fields &smartvase_SoftResetCommand_msg
#define smartvase_WrapperMessage_fields &smartvase_WrapperMessage_msg

/* Maximum encoded size of messages (where known) */
#define SMARTVASE_SMARTVASE_PB_H_MAX_SIZE        smartvase_WrapperMessage_size
#define smartvase_CommandResponse_size           81
#define smartvase_Command_size                   21
#define smartvase_Heartbeat_size                 25
#define smartvase_Log_size                       83
#define smartvase_ReadSoilCommand_size           0
#define smartvase_RequestDiagnosticsCommand_size 0
#define smartvase_SetModeCommand_size            2
#define smartvase_SetMotionParamsCommand_size    12
#define smartvase_SoftResetCommand_size          0
#define smartvase_StopCommand_size               0
#define smartvase_TelemetryDeep_size             111
#define smartvase_TelemetryFast_size             50
#define smartvase_WaterCommand_size              6
#define smartvase_WrapperMessage_size            113

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
