/*! @file SerialManager.h
 *  @ingroup HubSerial
 *  @brief Hub<->Mega serial framing: encapsulates/decapsulates `WrapperMessage`
 *  Protobuf messages over UART2 with a SOF/length header and CRC16-CCITT trailer.
 *  @author Giacomo Radin
 *  @date 2025-10-28
 */

/*! @defgroup HubSerial Serial communication with the Mega
 *  @brief Framing protocol (SOF, length, Protobuf payload, CRC16-CCITT) used
 *  over the UART2 link between the Hub and the Arduino Mega, plus the shared
 *  CRC utilities.
 */

#ifndef SERIALMANAGER_H
#define SERIALMANAGER_H

#include <Arduino.h>
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "freertos/task.h"

// Include the Protobuf definitions generated by Nanopb
// Assumed to live under the project's PlatformIO lib/nanopb folder
extern "C" {
  #include "pb_decode.h"
  #include "pb_encode.h"
  #include "smartvase.pb.h" // Your generated .pb.h file
}
#include "smartvase_aliases.h" // Your aliases, if you use them

/*! @addtogroup HubSerial
 *  @{
 */

/*!
 * @def SERIAL_BUFFER_SIZE
 * @brief Maximum size (bytes) of the Protobuf payload in the serial framing.
 * @note Must be greater than or equal to PROTOBUF_BUFFER_SIZE defined in the
 * Mega firmware, otherwise a frame that is valid on the Mega side would be
 * discarded here for exceeding the buffer (see handleSerialReception(),
 * WAIT_LEN_L state).
 */
#define SERIAL_BUFFER_SIZE 256                  ///< Size of the serial RX/TX buffer (bytes).
#define PROTOBUF_MAX_PAYLOAD SERIAL_BUFFER_SIZE  ///< Maximum Protobuf payload accepted in the framing (= SERIAL_BUFFER_SIZE).

/*! @name UART2 pins towards the Mega
 *  @{
 */
#define MEGA_RX_PIN 16 ///< ESP32 RX2 <- Mega TX1 (D18).
#define MEGA_TX_PIN 17 ///< ESP32 TX2 -> Mega RX1 (D19).
/*! @} */

/*!
 * @struct SerialMessage
 * @brief Wrapper around a Protobuf `WrapperMessage`, used as the element type
 * of the FreeRTOS `serialRxQueue`/`serialTxQueue` queues (see main.cpp).
 */
typedef struct {
    WrapperMessage message; /**< Copy of the decoded Protobuf message (RX) or the one to encode (TX). */
} SerialMessage;

/*!
 * @class SerialManager
 * @brief Body of the `TaskSerialMega` FreeRTOS task: manages UART2 towards
 * the Mega, decodes incoming frames and encapsulates/sends outgoing ones.
 * @details Framing: `0xAA | len_hi | len_lo | Protobuf payload (<=SERIAL_BUFFER_SIZE) | crc16_hi | crc16_lo`,
 * with CRC16-CCITT (poly 0x1021, init 0x0000, MSB-first) computed over the
 * payload only. A frame with an invalid CRC or length is silently discarded
 * (with an ERROR-level log) and the receive FSM returns to waiting for the
 * next SOF.
 * @note Only one instance runs in the TaskSerialMega task (Core 1, high
 * priority): the RX FSM state and the buffers are instance members (not
 * local statics), which makes the class reentrant in principle, though it is
 * not designed to be used by more than one task at the same time.
 */
class SerialManager {
public:
    /*! @brief Constructor: stores the handles of the FreeRTOS queues created in main.cpp.
     *  @param[in] rxQueue Queue on which to publish the Protobuf messages received from the Mega.
     *  @param[in] txQueue Queue from which to read the Protobuf messages to send to the Mega. */
    SerialManager(QueueHandle_t rxQueue, QueueHandle_t txQueue);

    /*! @brief Static entry point for `xTaskCreatePinnedToCore`: forwards to the instance's taskRun().
     *  @param[in] pvParameters Pointer to the SerialManager on which to run the task. */
    static void taskEntry(void* pvParameters);

    /*! @brief Initializes Serial2 (UART2) at 115200 baud on the MEGA_RX_PIN/MEGA_TX_PIN pins.
     *  @note Must be called exactly once in setup(), before the TaskSerialMega task is created. */
    void init();

private:
    QueueHandle_t _rxQueue; /**< Queue for messages RECEIVED from the Mega (consumed by MainLogic). */
    QueueHandle_t _txQueue; /**< Queue for messages TO SEND to the Mega (fed by MainLogic/HubCli). */

    uint8_t _rxBuffer[SERIAL_BUFFER_SIZE]; /**< Accumulation buffer for the incoming Protobuf payload. */
    uint8_t _txBuffer[SERIAL_BUFFER_SIZE]; /**< Encoding buffer for the outgoing Protobuf payload. */

    /*! @brief States of the serial framing receive FSM. */
    enum RxState {
        WAIT_SOF,     /**< Waiting for the Start Of Frame byte (0xAA). */
        WAIT_LEN_H,   /**< Waiting for the high byte of the payload length. */
        WAIT_LEN_L,   /**< Waiting for the low byte of the payload length; range is validated here. */
        WAIT_PAYLOAD, /**< Accumulating the Protobuf payload bytes into _rxBuffer. */
        WAIT_CRC_H,   /**< Waiting for the high byte of the CRC16. */
        WAIT_CRC_L    /**< Waiting for the low byte of the CRC16; the frame is validated and decoded here. */
    };
    // Receive FSM state kept as instance MEMBERS (reentrant class: no more
    // local static variables in handleSerialReception()).
    RxState  _rxState         = WAIT_SOF; /**< Current state of the RX FSM. */
    uint16_t _rxMessageLength = 0;        /**< Payload length declared by the current frame. */
    uint16_t _rxPayloadIndex  = 0;        /**< Number of payload bytes already accumulated in _rxBuffer. */
    uint16_t _rxReceivedCRC   = 0;        /**< CRC16 read from the frame, to be compared against the computed CRC. */

    /*! @brief Body of the `TaskSerialMega` FreeRTOS task: alternates non-blocking
     *  serial reads (handleSerialReception()) with sending (10 ms timeout) any
     *  messages present in `_txQueue`. */
    void taskRun();

    /*! @brief Advances the receive FSM, consuming all bytes currently available on Serial2.
     *  @details Upon receiving a complete frame with a valid CRC, decodes the
     *  payload as a `WrapperMessage` (nanopb) and pushes it onto `_rxQueue`.
     *  Frames with an out-of-range length, a wrong CRC, or a failed Protobuf
     *  decode are discarded (ERROR log) without propagating the error to the caller. */
    void handleSerialReception();

    /*! @brief Encodes a `WrapperMessage` as Protobuf and sends it to the Mega
     *  with the SOF/length/payload/CRC16-CCITT framing.
     *  @param[in] message Message to send.
     *  @return true if encoding and sending succeeded (including the edge
     *  case of an empty message, which is logged but not treated as an error);
     *  false if encoding fails or exceeds SERIAL_BUFFER_SIZE.
     *  @note Calls `Serial2.flush()`: blocks until the physical transmission
     *  of the bytes in the hardware TX buffer completes. */
    bool sendProtobufMessage(const WrapperMessage& message);
    // CRC16-CCITT in crc_utils (shared with ConfigManager).
};

/*! @} */ // end of HubSerial group

#endif // SERIALMANAGER_H
