[env:esp32cam]
platform = espressif32
board    = esp32cam
framework = arduino

monitor_speed = 115200
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    bblanchon/ArduinoJson @ ^6.19.4
    knolleary/PubSubClient @ ^2.8
