[env:megaatmega2560]
platform = atmelavr
board    = megaatmega2560
framework = arduino

monitor_speed = 115200
build_flags =
    -Wno-unknown-pragmas

lib_deps =
    adafruit/Adafruit BME680 Library @ ^2.0.1
    enjoyneering/HCSR04 @ ^1.1.0
    paulstoffregen/Time @ ^1.6.1
    jchristensen/DS3232RTC @ ^2.0.1
