/*!
    @file   smartvase_aliases.h

    @ingroup MegaMisc

    @brief  Aliases to nanopb protobuf symbols + Mega internal C++ types.

    @details Maps symbols generated by nanopb with prefix `smartvase_`
             (defined in `smartvase.pb.h`, regenerated from the `.proto` canonical
             in `infra/smartvase-proto/`) to the short names used in the rest of the
             firmware. Also contains C++ types used only on the Mega side
             (`DeviceConfig`, `CumulativeStats`, `CppMovementState`, `CppMode`)
             that are NOT part of the Protobuf protocol, kept
             deliberately separate from protobuf enums to not tie the
             internal logic to the network schema (vedi `cppMovementStateToProto`).

             Protobuf schema v4.0 — 2026-05-19 (total refactor post-new PIN map).

    @date   2025-10-20

    @author Giacomo Radin
*/

#ifndef SMARTVASE_ALIASES_H_INCLUDED
#define SMARTVASE_ALIASES_H_INCLUDED

#include "smartvase.pb.h"

/*!
    @addtogroup MegaMisc
    @{
*/

// --- Aliases for Types (Structs & Enums) ---
typedef smartvase_WrapperMessage         WrapperMessage;
typedef smartvase_Log_LogLevel           Log_LogLevel;
typedef smartvase_Command                Command;
typedef smartvase_CommandResponse_Status CommandResponse_Status;
typedef smartvase_MovementState          MovementState;
typedef smartvase_SetModeCommand_Mode    SetModeCommand_Mode;
typedef smartvase_TelemetryFast          TelemetryFast;
typedef smartvase_TelemetryDeep          TelemetryDeep;
typedef smartvase_Log                    Log;
typedef smartvase_Heartbeat              Heartbeat;
typedef smartvase_CommandResponse        CommandResponse;

// --- Message Descriptors ---
#define WrapperMessage_fields smartvase_WrapperMessage_fields

// --- Initialization Macros ---
#define WrapperMessage_init_zero    smartvase_WrapperMessage_init_zero
#define Log_init_zero               smartvase_Log_init_zero
#define Command_init_zero           smartvase_Command_init_zero
#define CommandResponse_init_zero   smartvase_CommandResponse_init_zero
#define TelemetryFast_init_zero     smartvase_TelemetryFast_init_zero
#define TelemetryDeep_init_zero     smartvase_TelemetryDeep_init_zero
#define Heartbeat_init_zero         smartvase_Heartbeat_init_zero

// --- 'oneof' Field Tags ---
#define WrapperMessage_telemetry_fast_tag   smartvase_WrapperMessage_telemetry_fast_tag
#define WrapperMessage_telemetry_deep_tag   smartvase_WrapperMessage_telemetry_deep_tag
#define WrapperMessage_log_tag              smartvase_WrapperMessage_log_tag
#define WrapperMessage_heartbeat_tag        smartvase_WrapperMessage_heartbeat_tag
#define WrapperMessage_command_tag          smartvase_WrapperMessage_command_tag
#define WrapperMessage_command_response_tag smartvase_WrapperMessage_command_response_tag

#define Command_water_tag                 smartvase_Command_water_tag
#define Command_set_mode_tag              smartvase_Command_set_mode_tag
#define Command_stop_tag                  smartvase_Command_stop_tag
#define Command_request_diagnostics_tag   smartvase_Command_request_diagnostics_tag
#define Command_set_motion_params_tag     smartvase_Command_set_motion_params_tag
#define Command_read_soil_tag             smartvase_Command_read_soil_tag
#define Command_soft_reset_tag            smartvase_Command_soft_reset_tag

// --- Enum Values ---
#define Log_LogLevel_INFO      smartvase_Log_LogLevel_INFO
#define Log_LogLevel_WARN      smartvase_Log_LogLevel_WARN
#define Log_LogLevel_ERROR     smartvase_Log_LogLevel_ERROR
#define Log_LogLevel_CRITICAL  smartvase_Log_LogLevel_CRITICAL

#define CommandResponse_Status_OK    smartvase_CommandResponse_Status_OK
#define CommandResponse_Status_ERROR smartvase_CommandResponse_Status_ERROR

#define SetModeCommand_Mode_IDLE   smartvase_SetModeCommand_Mode_IDLE
#define SetModeCommand_Mode_LIGHT  smartvase_SetModeCommand_Mode_LIGHT
#define SetModeCommand_Mode_SHADOW smartvase_SetModeCommand_Mode_SHADOW

#define MS_IDLE            smartvase_MovementState_M_IDLE
#define MS_MOVING          smartvase_MovementState_M_MOVING
#define MS_AVOID_START     smartvase_MovementState_M_AVOID_START
#define MS_AVOID_REVERSING smartvase_MovementState_M_AVOID_REVERSING
#define MS_AVOID_TURNING   smartvase_MovementState_M_AVOID_TURNING
#define MS_STUCK           smartvase_MovementState_M_STUCK

// =================================================================
// Internal C++ types (not Protobuf)
// =================================================================

/*!
    @struct DeviceConfig
    @brief  Device configuration persisted in EEPROM (dual-slot, see Persistence.h).
*/
typedef struct {
    uint32_t magic_number;       /**< Magic number to validate the EEPROM slot. */
    uint16_t crc16;               /**< CRC16-CCITT of the struct (see Crc16.h), validated on load. */
    uint16_t write_counter;       /**< Write counter for dual-slot wear-leveling. */
    uint8_t  motorCalibLeft;      /**< Left motor calibration PWM, 0..255. */
    uint8_t  motorCalibRight;     /**< Right motor calibration PWM, 0..255. */
    uint16_t avoid_reverse_ms;    /**< Reverse duration during obstacle avoidance, in ms. */
    uint16_t avoid_turn_ms;       /**< Rotation duration during obstacle avoidance, in ms. */
    uint16_t soil_dry_threshold;  /**< Soil ADC threshold below which the soil is considered 'dry'. */
    uint16_t light_threshold;     /**< Brightness ADC threshold for light/shadow seeking inversion. */
    uint16_t tank_empty_cm;       /**< Distance US4->water (cm) beyond which the tank is considered empty (pump blocked). */
    // --- Autonomous plant care (L2 layer, see CarePolicy.h / Care.cpp) ---
    uint8_t  care_enabled;            /**< 1 = autonomous care active (default 0: explicitly enabled with `care on`). */
    uint8_t  care_plant_kind;         /**< Active plant preset (CarePlantKind: 0=shade, 1=medium, 2=sun). */
    uint16_t care_light_target_min;   /**< Daily light target, in equivalent full light minutes. */
    uint16_t care_lux_high_adc;       /**< ADC above which prolonged exposure triggers shadow seeking (1024 = never). */
    uint16_t care_soil_wet_adc;       /**< Soil ADC at/above which the irrigation cycle stops (hysteresis with soil_dry_threshold). */
    uint16_t care_dose_ms;            /**< Duration of a single irrigation dose (ms). */
    uint8_t  care_soak_min;           /**< Absorption wait between two doses (minutes). */
    uint8_t  care_max_doses;          /**< Daily doses cap (fail-safe for broken fork). */
    uint8_t  care_max_reloc;          /**< Daily relocations cap (anti-nomadism). */
    uint8_t  care_growlight_max_min;  /**< Daily cap for UVA light top-up (minutes). */
} DeviceConfig;

/*!
    @struct CumulativeStats
    @brief  Cumulative usage statistics persisted in EEPROM (dual-slot, see Persistence.h).
*/
typedef struct {
    uint32_t magic_number;                  /**< Magic number to validate the EEPROM slot. */
    uint16_t crc16;                          /**< CRC16-CCITT of the struct (see Crc16.h), validated on load. */
    uint16_t write_counter;                  /**< Write counter for dual-slot wear-leveling. */
    uint32_t total_motor_active_time_s;      /**< Cumulative motor active time, in seconds. */
    uint32_t total_irrigations;              /**< Total number of irrigations performed. */
    uint32_t total_irrigation_duration_s;    /**< Cumulative duration of irrigations, in seconds. */
    uint32_t light_seeking_sessions;         /**< Number of light seeking sessions (LIGHT mode). */
    uint32_t shadow_seeking_sessions;        /**< Number of shadow seeking sessions (SHADOW mode). */
    uint32_t obstacles_avoided;              /**< Number of successfully avoided obstacles. */
    uint32_t escape_attempts;                /**< Number of anti-circling relocation attempts during seeking. */
    uint32_t stuck_events;                   /**< Number of times the robot entered the M_STUCK state. */
    uint32_t watchdog_resets;                /**< Number of resets caused by the watchdog timer. */
    uint32_t bme_read_errors;                /**< Number of read errors from the BME680 sensor. */
    uint32_t log_overflows;                  /**< Number of times the circular log queue discarded INFO entries due to overflow. */
    uint32_t pb_decode_failures;             /**< Number of serial frames discarded due to protobuf decoding or CRC failure. */
} CumulativeStats;

/*!
    @enum  CppMovementState
    @brief State of the movement state machine, C++ side.

    @details Kept as a separate type from the `MovementState` protobuf enum to
             not tie the internal logic of main to the network schema; the
             conversion to the protobuf type happens explicitly with
             ::cppMovementStateToProto.
*/
typedef enum {
    CPP_M_IDLE,            /**< Robot stopped, no active target movement. */
    CPP_M_MOVING,           /**< Normal movement (light/shadow seeking or no search). */
    CPP_M_AVOID_START,      /**< Entry into the obstacle avoidance sequence. */
    CPP_M_AVOID_REVERSING,  /**< Reverse phase of obstacle avoidance. */
    CPP_M_AVOID_TURNING,    /**< Rotation phase of obstacle avoidance. */
    CPP_M_STUCK,            /**< Robot stuck, waiting for backoff before a new attempt. */
    CPP_M_SCAN_ROTATE,      /**< Light scan: rotation in place sampling the LDR by sectors (see startLightScan). */
    CPP_M_SCAN_ALIGN        /**< Light scan: second rotation to the best identified sector. */
} CppMovementState;

/*!
    @enum  CppMode
    @brief Robot operating modes (set via CLI or Hub `setMode` command).
*/
typedef enum {
    CPP_IDLE,    /**< No active search: the robot stays still if not in manual movement. */
    CPP_LIGHT,   /**< Search for light (light seeking). */
    CPP_SHADOW   /**< Search for shadow (shadow seeking). */
} CppMode;

/*!
    @brief    Converts a C++ movement state into the corresponding protobuf enum.

    @param[in] s Movement state on the C++ side.

    @return   The equivalent ::MovementState value to send in `TelemetryFast`.

    @note     `CPP_M_IDLE` and any unrecognized value map to `MS_IDLE` (fail-safe default).
*/
static inline MovementState cppMovementStateToProto(CppMovementState s) {
    switch (s) {
        case CPP_M_MOVING:          return MS_MOVING;
        // Internal light scan states are a form of active movement:
        // towards the network schema (v4.0, no scan states) they are reported as MOVING.
        case CPP_M_SCAN_ROTATE:     return MS_MOVING;
        case CPP_M_SCAN_ALIGN:      return MS_MOVING;
        case CPP_M_AVOID_START:     return MS_AVOID_START;
        case CPP_M_AVOID_REVERSING: return MS_AVOID_REVERSING;
        case CPP_M_AVOID_TURNING:   return MS_AVOID_TURNING;
        case CPP_M_STUCK:           return MS_STUCK;
        case CPP_M_IDLE:
        default:                    return MS_IDLE;
    }
}

/*! @} */ // MegaMisc

#endif // SMARTVASE_ALIASES_H_INCLUDED
