/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "smartvase.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(smartvase_TelemetryFast, smartvase_TelemetryFast, AUTO)


PB_BIND(smartvase_TelemetryDeep, smartvase_TelemetryDeep, AUTO)


PB_BIND(smartvase_Log, smartvase_Log, AUTO)


PB_BIND(smartvase_Heartbeat, smartvase_Heartbeat, AUTO)


PB_BIND(smartvase_Command, smartvase_Command, 2)


PB_BIND(smartvase_CommandResponse, smartvase_CommandResponse, 2)


PB_BIND(smartvase_WaterCommand, smartvase_WaterCommand, AUTO)


PB_BIND(smartvase_SetModeCommand, smartvase_SetModeCommand, AUTO)


PB_BIND(smartvase_SetMotionParamsCommand, smartvase_SetMotionParamsCommand, AUTO)


PB_BIND(smartvase_StopCommand, smartvase_StopCommand, AUTO)


PB_BIND(smartvase_RequestDiagnosticsCommand, smartvase_RequestDiagnosticsCommand, AUTO)


PB_BIND(smartvase_ReadSoilCommand, smartvase_ReadSoilCommand, AUTO)


PB_BIND(smartvase_SoftResetCommand, smartvase_SoftResetCommand, AUTO)


PB_BIND(smartvase_WrapperMessage, smartvase_WrapperMessage, AUTO)











